import "./globals.css";
import Header from "@/components/Header";
import localFont from 'next/font/local';
import Footer from "@/components/Footer";
import type { Metadata } from "next";

const clashDisplay = localFont({
  src: [
    {
      path: '../font/ClashDisplay-Regular.ttf',
      weight: '500',
      style: 'normal',
    },
  ],
  variable: '--font-clash-display',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${clashDisplay.variable} bg-white `}>
        <Header />
        <div>
          <main className=" bg-white">
            {children}
          </main>
        </div>
        <Footer />
      </body>
    </html>
  );
}
